### ISSUE TITLE
[Ember 4.5] Invalid modifier manager compatibility specified

### ISSUE THREAD

**Issue by gwak** [adopted-ember-addons/ember-file-upload#825] opened 2022-07-22 08:47 UTC
Hi,

When installing `ember-file-upload@7.0.2` add-on to a `ember-source@4.5.0` app, I get the following error at runtime:
`Error: Invalid modifier manager compatibility specified`.

```js
Uncaught (in promise) Error: Invalid modifier manager compatibility specified
    at modifierCapabilities (manager.js:833:1)
    at __WEBPACK_DEFAULT_EXPORT__.setupListener._this (file-queue-d04ff673.js:6:29)
    at CustomModifierManager.getDelegateFor (manager.js:882:1)
    at CustomModifierManager.create (manager.js:898:1)
    at Object.evaluate (runtime.js:2772:1)
    at AppendOpcodes.evaluate (runtime.js:1312:1)
    at LowLevelVM.evaluateSyscall (runtime.js:5178:1)
    at LowLevelVM.evaluateInner (runtime.js:5134:1)
    at LowLevelVM.evaluateOuter (runtime.js:5126:1)
    at VM.next (runtime.js:6137:1)
```

I have the following dependencies:
```js
"ember-source": "4.5.0",
"ember-file-upload": "7.0.2",
"ember-modifier": "3.2.7", // Also tried "4.0.0-beta.1",
"@embroider/compat": "1.8.3",
"@embroider/core": "1.8.3",
"@embroider/router": "1.8.3",
"@embroider/webpack": "1.8.3",
"webpack": "5.73.0"
```

**Comment by jelhan** [comment] 2022-07-22 09:24
This addon is tested with latest Ember release and `ember-modifier@^3.2.7`. Maybe another addon pulls in an outdated version of `ember-modifier`? You could check that by running `yarn why ember-modifier` in your app. It should only report one version and that one should match `^3.2.7`. Using multiple versions of ember-modifier at run-time in parallel is not supported.

**Comment by gilest** [comment] 2022-07-22 10:48
Hey @gwak 👋🏻 . Thank you for reporting. I tried to repro your issue by creating a new app with the dependencies you listed but it builds and runs normally.

Suggest you check your package manager's lockfile to see if you have conflicting versions of `ember-modifier`. You may want to use [yarn resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) or [npm overrides](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) to make sure the correct version of `ember-modifier` shows up in your build.

**Comment by gilest** [comment] 2022-07-23 00:43
Closing due to lack of reproduction. Let us know if you can't resolve.

**Closed by gilest** 2022-07-23 00:43 UTC
