### ISSUE TITLE
Getting file type as empty string in case of font files

### ISSUE THREAD

**Issue by 21Aby** [adopted-ember-addons/ember-file-upload#778] opened 2022-05-19 12:16 UTC
While trying to upload some font files ( `font/otf` & `font/ttf` ), the uploaded file type is an `empty string`. This in-turn fails my S3 upload operation ( since the file doesn't have the supposed type )

Is this because of a missing support for the above mentioned types or any other particular issues ?

Also Is there a way to set the file type by myself ( Right now, Can't set directly, since the properties are defined as getter only )

Please update

**Comment by gilest** [comment] 2022-05-20 05:45
Hey @21Aby thank you for reporting.

I tried to reproduce this in Chrome with random fonts from my system but the type property worked as expected.

Could you please share:

- Version of `ember-file-upload` that you are using
- Name and version of browser you are using
- If possible, the specific font files you are testing
- If you want to be really helpful, a minimal reproduction in a public repo

**Comment by 21Aby** [comment] 2022-05-20 08:35
@gilest Thank you for the response

- "ember-file-upload": "5.1.0"
- Chrome ( Version 101.0.4951.64 (Official Build) (x86_64) )
- I tried with the `.otf` & `.ttf` types from https://dl.dafont.com/dl/?f=mabook (Sorry, Attaching font file not supported )

![Screenshot 2022-05-20 at 1 50 36 PM](https://user-images.githubusercontent.com/37609856/169486494-c785dc12-4a4b-40e9-89d1-276bd80c2981.png)

**Comment by gilest** [comment] 2022-05-21 04:11
Strange. We only proxy the value of the native File object. 

I checked the type of both files using the addon itself and [on MDN's File.type page](https://developer.mozilla.org/en-US/docs/Web/API/File/type) and the types show up correctly for me.

Can you try the tool linked above and let me know your results.

<img width="795" alt="Screen Shot 2022-05-21 at 4 06 14 PM" src="https://user-images.githubusercontent.com/36919/169634805-5263e994-bbde-4d9d-8a51-687b2a6806b1.png">
<img width="800" alt="Screen Shot 2022-05-21 at 4 06 22 PM" src="https://user-images.githubusercontent.com/36919/169634807-5cc04c3d-0111-4d37-ac75-471bf2c0ab24.png">

According to MDN

> Based on the current implementation, browsers won't actually read the bytestream of a file to determine its media type. It is assumed based on the file extension; a PNG image file renamed to .txt would give "text/plain" and not "image/png". Moreover, file.type is generally reliable only for common file types like images, HTML documents, audio and video. Uncommon file extensions would return an empty string. Client configuration (for instance, the Windows Registry) may result in unexpected values even for common types. Developers are advised not to rely on this property as a sole validation scheme.

I'm not really sure what's happening downstream of this with S3 but I'm not sure there's anything I can change in this addon which will help you.

**Comment by 21Aby** [comment] 2022-05-21 12:22
@gilest You were right. The issue is not with the add-on. 

- Tried [MDN's File.type page](https://developer.mozilla.org/en-US/docs/Web/API/File/type) in Chrome, Safari, Firefox & Edge. Got the same results😐 . 
- Tried with a Windows system ( previous tests were done on Mac ) & chrome browser & still the same Issue.
- Tried in my Android Phone & It Worked..

![Screenshot 2022-05-21 at 5 23 27 PM](https://user-images.githubusercontent.com/37609856/169650639-4a7f7ee8-f8ff-4522-aeda-888c48bfc197.png)

![Screenshot 2022-05-21 at 5 23 42 PM](https://user-images.githubusercontent.com/37609856/169650642-8f378c71-a0c7-443b-8a9c-9b7c62438489.png)

![Screenshot 2022-05-21 at 5 24 03 PM](https://user-images.githubusercontent.com/37609856/169650646-1cebb58e-8728-4ef7-9472-f404ff87795a.png)

------------------
> I'm not really sure what's happening downstream of this with S3

I tried the same with a Postman request ( same file ) & Its working fine. And I think the missing `file.type` is causing the issue

**I'm not sure, but what are your thoughts on adding a custom setter property for file type ( to handle cases like this ) ? Or, Is there any other way to achieve the same ?**

**Comment by jelhan** [comment] 2022-05-21 14:28
> I'm not sure, but what are your thoughts on adding a custom setter property for file type ( to handle cases like this ) ? Or, Is there any other way to achieve the same ?

Maybe the `onFileAdded` event of `file-queue` helper could allow to replace added file by returning another `UploadFile` instance? I think this would provide most flexibility while keeping `UploadFile` immutable.

Maybe same feature could be added to `onFileSelected` event of the `selectFile` modifier. Not sure which fits best. Or if it should be both.

**Comment by gilest** [comment] 2022-05-25 00:26
> Maybe the `onFileAdded` event of `file-queue` helper could allow to replace added file by returning another `UploadFile` instance?

Interesting. I wonder if the callback API having an additional usage might be confusing and hard to teach/remember.

> while keeping `UploadFile` immutable

UploadFile is already a mutable object. There are existing setters for `name`, `size` and `state`.

I think I could implement a setter for `type` which replaces the underlying [File](https://developer.mozilla.org/en-US/docs/Web/API/File/File) with a new copy created with the expected `type`.

What do you both think?

**Comment by gilest** [comment] 2022-05-26 00:12
Staged a possible API in #795 . I think the method name could be improved

**Comment by 21Aby** [comment] 2022-05-26 03:57
@gilest 

> I think I could implement a setter for type which replaces the underlying [File](https://developer.mozilla.org/en-US/docs/Web/API/File/File) with a copy of File with the expected type.

I tried adding a custom setter for `type` just like the others you have mentioned in `UploadFile` 

```
	#type = '';

	get type(): string {
		return this.#type || this.file.type;
	}

	set type(value) {
		this.#type = value;
	}
```

 & It resolved the s3 issue ( as expected ).

Thank you so much for the PR ❣️

**Comment by gilest** [comment] 2022-05-30 00:49
Interesting. I thought you were using the underlying `File` object somehow and needed its type to be changed.

Are you using `file.upload()` to do your S3 upload?

If yes then could you try setting `contentType` as an option.

For example:

```js
export default class ExampleComponent extends Component {
  @action
  async uploadPhoto(file) {
    try {
      const response = await file.upload('/api/images/upload', { contentType: 'font/otf' });
    } catch (error) {
      file.state = 'aborted';
    }
  }
}
```

I've just found that the `UploadOptions` are not documented, I will add some docs for them today 😅

**Comment by gilest** [comment] 2022-05-31 23:16
@21Aby did you have a chance to try my suggestion?

**Comment by 21Aby** [comment] 2022-06-01 14:06
@gilest Sorry for the delay.

I tried adding the corresponding type in the `contentType` as you suggested and the file gets successfully uploaded to S3😅. I was under the misconception for that missing file type to be the primary cause of the issue. 

Speaking of which, you won't discard the `replaceWithType` feature, right? 😬

**Comment by 21Aby** [comment] 2022-06-06 12:23
@gilest 

As of now, the fix you suggested on `contentType` works fine for me & there is no need of manually setting the type. 

But again I'm a little confused. In my personal opinion, I would like to have that `replaceWithType` feature included ( if there is a need for, in the future). And the rest is upto you guys

**Comment by gilest** [comment] 2022-06-11 01:07
Thanks for getting back @21Aby . Since setting `contentType` is working I'm going to close this issue now.

I don't really want to ship a new feature if no one will use it – not good for bundle size 😬

**Closed by gilest** 2022-06-11 01:07 UTC
Labels: bug
