### ISSUE TITLE
Move `mirage` folder outside of `addon` folder

### ISSUE THREAD

**Issue by bertdeblock** [adopted-ember-addons/ember-file-upload#425] opened 2021-03-30 11:27 UTC
By default everything included in the `addon` folder ships. Since Mirage is a mocking tool, related code should not be included in the final build (at least not automagically).

<img width="173" alt="Screenshot 2021-03-30 at 13 20 29" src="https://user-images.githubusercontent.com/7403183/112980994-df0a2400-915a-11eb-8517-01cb66ec3d48.png">

Maybe the same can be accomplished by moving it to the `addon-test-support` folder, but haven't tested this myself.

**Comment by bendemboski** [comment] 2021-04-15 00:04
This also breaks embroider builds

**Comment by gilest** [comment] 2021-04-15 02:57
Thanks for reporting. I've created a PR that simply moves those files into `addon-test-support`.

@bendemboski would you mind testing this with a static Embroider build?

I'll get the `ember-try` scenarios added soon.

**Comment by bertdeblock** [comment] 2021-04-15 06:12
I noticed that `ember-cli-mirage` isn't in `dependencies`. Could that be related to the embroider issue?

**Comment by gilest** [comment] 2021-04-15 06:28
> I noticed that `ember-cli-mirage` isn't in `dependencies`. Could that be related to the embroider issue?

Yeah certainly could be. I think the idea in the past was to ship mirage route handlers with the addon in case users wanted to use them in application tests.

I'm not sure it's worth adding `ember-cli-mirage` to `dependenices` for this purpose. Perhaps the handlers could go in a separate package?

I'm trying to get CI/ember-try back up. Should have a better idea of compatibility then...

**Comment by jelhan** [comment] 2021-04-15 09:26
> I noticed that `ember-cli-mirage` isn't in `dependencies`. Could that be related to the embroider issue?

Yes. Embroider should break due to this. Embroider is more strict about explicit listing all dependencies, which are used. A package from `ember-cli-mirage` is imported here: https://github.com/adopted-ember-addons/ember-file-upload/blob/556075f97c2ceada0ac11c3bcfbd734b84bd6245/addon/mirage/index.js#L2

If I didn't missed something it is the only place at which `ember-cli-mirage` is imported. Mirage's `Reponse` class is used at two places in the route handler: https://github.com/adopted-ember-addons/ember-file-upload/blob/556075f97c2ceada0ac11c3bcfbd734b84bd6245/addon/mirage/index.js#L49 https://github.com/adopted-ember-addons/ember-file-upload/blob/556075f97c2ceada0ac11c3bcfbd734b84bd6245/addon/mirage/index.js#L55

If I recall correctly the same can be achieved in Mirage without returning an instance of `Response` class. This would allow us to drop the dependency.

**Comment by jelhan** [comment] 2021-04-15 09:28
> Maybe the same can be accomplished by moving it to the `addon-test-support` folder, but haven't tested this myself.

The mirage handlers are needed whenever mirage is used. Often that is only the case for builds, which include tests. But there are also use cases to include mirage but not tests. Please see also my comment here: https://github.com/adopted-ember-addons/ember-file-upload/pull/427#issuecomment-820200366

**Comment by bertdeblock** [comment] 2021-04-15 09:31
I'm not super familiar with this addon and the reason it contains these mirage helpers, I assumed it was to mock during tests, but I didn't take into account mocking during development. So I'm aware my suggestion wasn't probably to best thing to do, it was the first thing that come to mind when creating the issue 😄.

**Comment by jelhan** [comment] 2021-04-15 09:34
The mirage handlers are part of the public API. They are not only used to test and develop this addon but also exposed to consumers to allow them to mock file uploading.

**Comment by bertdeblock** [comment] 2021-04-15 09:37
That's what I meant with mocking during tests and development yes.

**Comment by bendemboski** [comment] 2021-04-17 16:22
> If I recall correctly the same can be achieved in Mirage without returning an instance of Response class. This would allow us to drop the dependency.

Unless there's some mechanism I'm not aware of, it's not possible to provide a dynamic custom status code response (like `ember-file-upload`'s mirage route helper does for the timeout and error responses) without returning a `Response` -- see [this](https://github.com/miragejs/miragejs/blob/d81a6b74dc341d5395ee948b5e935af004aa367e/lib/route-handler.js#L111-L141) code -- you either return a `Response` or you just return the response body data, and it uses your handler's statically configured response code or falls back on the default response code for the handler's HTTP verb.

**Comment by jelhan** [comment] 2021-04-17 19:03
Mirage had an option to provide a response code as second argument on route handler registration:

```js
this.verb(path, handler[, responseCode, options={}]);
```

I wasn't able to find it in documentation for Ember CLI Mirage >= 1.0. But Mirage seems to still have code related to it: https://github.com/miragejs/miragejs/blob/master/lib/server.js#L1035-L1060 I also wasn't able to find it mentioned in upgrade guides. Sadly the route handler registration methods seem to miss in API Docs as well. Long story short: I'm not sure if the functionality was deprecated or just missed to be documented for >= 1.0. 🤷‍♂️

**Comment by jelhan** [comment] 2021-04-17 19:03
> Mirage had an option to provide a response code as third argument on route handler registration:
> 
> ```js
> this.verb(path, handler[, responseCode, options={}]);
> ```
> 
> I wasn't able to find it in documentation for Ember CLI Mirage >= 1.0. But Mirage seems to still have code related to it: https://github.com/miragejs/miragejs/blob/master/lib/server.js#L1035-L1060 I also wasn't able to find it mentioned in upgrade guides. Sadly the route handler registration methods seem to miss in API Docs as well. Long story short: I'm not sure if the functionality was deprecated or just missed to be documented for >= 1.0. 🤷‍♂️

**Comment by bendemboski** [comment] 2021-04-17 19:19
@jelhan the issue is that the route handler dynamically returns different status codes for the success/timeout/other error cases. The other error case could probably be removed since mirage already has a catch handler that generated a 500 response, but unless we drop the timeout response functionality, we can't have the route statically specify a status code -- it has to return one dynamically which AFAIKT requires a `Response` object.

I have an idea that I'm testing out, which is to dynamically import the `Response` class using `window.require()` from inside the route handler. At that point we know mirage is running, so it should be safe, and shouldn't be subject to any static analysis that will mess up embroider.

**Comment by bendemboski** [comment] 2021-04-18 16:12
I realize that I kinda hijacked this issue -- it does cause embroider build issues, but that's not what the issue is actually about, and my dynamic import fix for the embroider build doesn't address this issue, which is that `ember-file-upload` is shipping Mirage code into apps' production builds when that's almost never wanted.

So I can make that code build under embroider as a near-term solution for embroider compatibility, but we should probably stlll look into not adding Mirage code to the build when Mirage itself is not being added (and then the dynamic import solution would not be necessary).

IMO @bertdeblock had a smart idea with [this comment](https://github.com/adopted-ember-addons/ember-file-upload/pull/427#issuecomment-820297407), so I've opened [an issue](https://github.com/miragejs/ember-cli-mirage/issues/2166) and corresponding [PR](https://github.com/miragejs/ember-cli-mirage/pull/2167) with my proposed solution over in `ember-cli-mirage`. We'll see if they get any traction.

Perhaps we should file a separate issue tracking the embroider build failure, and either resolve it by merging #432, or port [this solution](https://github.com/kloeckner-i/ember-cli-mirage-graphql/blob/9e2b7c0240cf753e2cfe3a42c49bfae6653c0c4e/index.js#L37-L49) to `ember-file-upload` and then wait for a resolution to https://github.com/miragejs/ember-cli-mirage/issues/2166 to switch to a public API.

Thoughts?

**Comment by gilest** [comment] 2021-10-15 23:38
Resolved in #567

**Closed by gilest** 2021-10-15 23:38 UTC
