### ISSUE TITLE
Access to Dropzone Files in Events

### ISSUE THREAD

**Issue by dja** [adopted-ember-addons/ember-file-upload#39] opened 2017-05-18 00:29 UTC
I'm trying to use the actions on the `{{file-dropzone}}` component `ondragenter`, `ondragleave`, and `ondrop`, and I need to access the files that are being dragged in for a few reasons.. Is there a current way to achieve this, or can this be easily implemented?

- Validate the files against the `file-upload` attributes like `accept` and `multiple` (primarily `accept` so I can visually reject the file(s) being dragging over the dropzone, by outlining in red, etc)
- Run other custom validations in JS in the route action

*When testing this out currently, the event data I see in the console doesn't have any files in the queue, FileList, or DataTransferItemList

**Comment by tim-evans** [comment] 2017-05-18 14:04
It's not possible to access files during drag and drop due to security reasons by browsers.

You'd need to validate actual files during drop or browse events. You definitely could validate the number of files and the file type, but not any other properties.

**Comment by dja** [comment] 2017-05-18 17:54
Is that why the `ondrop` action doesn't provide any data about the files in the list?

**Comment by tim-evans** [comment] 2017-05-23 14:43
Oh, `ondrop` should definitely do that. If it doesn't, that's a bug.

**Comment by jelhan** [comment] 2020-02-27 23:51
Do you still face this issue on latest release? Even on latest master? If so please provide a reproduction. Will close the issue otherwise.

**Closed** 2020-03-09 22:56 UTC
